finished app
liviuclement/ricknmorty pull request #1
Opened 2022-10-05 08:03 UTC by liviuclement

2022-10-06 11:01 UTC, panciumihai requested changes
Te rog sa verifici consola sa nu aiba warnings create de tine inainte de un PR.

![image](https://user-images.githubusercontent.com/22646067/194295891-df38e84c-c0af-42a3-b8d0-9d170efb12e8.png)

Ca si urmator pas te rog sa rezolvi din comentarii iar unde ai nevoie de detalii, imi poti scrie.

2022-10-06 11:01 UTC, panciumihai commented on src/App.scss
> +  .main-container {
Recomandarea mea aici este sa folosesti o singura conventie de nume. De cele mai multe ori se foloseste camelCase in special la module dar este in regula si kebab-case pentru .scss normale

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterCard/CharacterCard.tsx
> +    locationName: string
Un card nu are nevoie de aceasta informatie. Cel mai simplu se putea trimite o proprietate onClick care sa fie pusa la randul ei pe card.

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterCard/CharacterCard.tsx
> +const CharacterCard = forwardRef((props: Props, ref: ForwardedRef<any>) => {
Nu era nevoie de ref pe card in contextul actual. Pentru infinite scroll se poate implementa un addEventListener pe scroll in CharactersList.

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterCard/CharacterCard.tsx
> +    return ref ? <Link
Evita sa dai return in acest fel in special cand ai chestii mai lungi. De asemeanea cand vrei sa verifici un ref, folsoeste ref.current

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterCard/CharacterCard.tsx
> +            className={`${styles.status} ${styles[status.toLowerCase()]}`}
${styles[status.toLowerCase()] daca trimit status "half-dead" cum se va afisa?

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterCard/CharacterCard.tsx
> +        <img
Puteai sa dai toata treaba asta intr-un div si puneai acel onClick pe el

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterList/CharacterList.module.scss
> +  grid-template-columns: 1fr 1fr 1fr;
Folosire buna a grid-ului

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterList/CharacterList.tsx
> +        if (characters.length === i + 1) {
Aici daca voiai sa verifici ultimul element e mai usual sa scrii asa: i === characters.length -1.

Insa aceasta verificare nu mai era necesara daca se folosea abordarea cu addEventListener pe scroll

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterList/CharacterList.tsx
> +        return <CharacterCard
Incearca sa regandesti treaba asta pentru a nu mai duplica < CharacterCard />. Rezultatul final trebuie sa contina un simplu map pe CharacterCard.

2022-10-06 11:01 UTC, panciumihai commented on src/components/CharacterList/CharacterList.tsx
> +            key={character.id}
Ai folosit bine key-ul.

2022-10-06 11:01 UTC, panciumihai commented on src/components/ErrorPage.tsx
> +export default function ErrorPage() {
Acest fisier cred ca trebuia sa fie in pages

2022-10-06 11:01 UTC, panciumihai commented on src/components/ErrorPage.tsx
> +    console.error(error);
sterge asta

2022-10-06 11:01 UTC, panciumihai commented on src/components/ErrorPage.tsx
> +export default function ErrorPage() {
Daca folosesti in restul proiectul arrow functions ar fi bine sa pastram o consistenta.

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +}
Evita sa trimiti state-uri asa. Aici mergea simplu cu 2 props: value si onChange

`
value: {status?: string, species?: string, gender?: string},


onChange: (value:  {status?: string, species?: string, gender?: string}) => {}
`

Desigur interfata mentionata sa fie declarata separat

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +        setOpenedSlice(prevOpenedSlice => prevOpenedSlice === slice ? '' : slice)
Nu vad rolul acestor wrappere. Le-am mai vazut in alta parte

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +    const [openedSlice, setOpenedSlice] = useState('');
Mi-a luat un pic sa inteleg ca aici te referi defapt la contentul deschis din acordion. Un nume mai sugestiv cred ca ar fi Content in loc de Slice. Oricum ceva mai sugestiv

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +    const onClearFilters = () => {
Functiile declarate in componenta, care sunt trimise la eventuri ar trebui denumite  ceva de genul in cazul asta. Exemplu: clearFilterClickHandler si asta ar ajunge sa fie folosita asa onClick={clearFilterClickHandler }

onClearFilters ar fi mers daca venea ca parametru.

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +                    <div className={`${styles.header} ${openedSlice === 'status' ? styles.opened : ''}`}
Foloseste classNames sau clsx pentru a controla clasele de stiluri

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +                        <img
Ai duplicat mult cod cu aceste acordion. Acordionul trebuie scos intr-o componenta separata care poate fi reutilizata. De exemplu puteai face un map cu content dinamic in loc sa hardcodezi fiecare sageata de colapsare.

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +export default CharactersFilter;
Concluzia aici e ca trebuie sa ai un accordion separat care sa fie folosit aici cu datele aferente.

2022-10-06 11:01 UTC, panciumihai commented on src/components/Header/Header.tsx
> +import { Link, RouteObject, useLocation } from "react-router-dom";
RouteObject nu este folosit

2022-10-06 11:01 UTC, panciumihai commented on src/components/Header/Header.tsx
> +                <Link to={'/'} className={isRoute('/') ? styles.active : ''}>Characters</Link>
Aici puteai folosi NavLink in loc de acest hack.

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +
De ce ai preferat sa separi asa tare store.ts de slices? Ma refer la ierarhia de fisiere.
Ce altceva ar mai putea contine features avand in vedere structura actuala?

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +            const { data } = await axios(`https://rickandmortyapi.com/api/character?page=${page}&status=${statusFilter || ''}&gender=${genderFilter || ''}&species=${speciesFilter || ''}`);
URL-ul trebuie scos intr-o constanta iar axios trebuie instantiat in alta parte.
Adica vei avea un fisier api unde vei initializa axios cu base path-ul tau si apoi acea instanta va fi folosita aici.

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +                    results: data.results.map((result: Character) => ({
nu mai era necesara aceasta mapare. Poti scrie direct **results: data.results**

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +export interface InitialState {
Redenumeste asta in CharactersState, cu atat mai mult ca este exportata.

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +            const { data } = await axios(`https://rickandmortyapi.com/api/character/${character}`);
aceasi poveste si aici

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +                state.status = 'idle';
statusul de idle este folosit doar cand nu se face nimic sau se face un clear. Aici ar trebui pus succeeded

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +                state.error = action.payload as any;
pai ori e string ori nu mai e

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +            .addCase(getCharacters.fulfilled, (state, action) => {
aici as fi facut 2 actiuni separate. Una de get character si alta de load more. In felul acesta avem 2 actiuni simple in loc de una complicata

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +						<div className={styles.content}>
Butoanele astea pot fi create dinamic din componenta generica de acordion mentionata anterior.

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +                state.characters = initialState.characters;
chiar vrei sa stergi datele daca pica un request? Mai bine afisezi o eroare si lasi pagina intacta, e mai user friendly

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +                state.status = 'idle';
same

2022-10-06 11:01 UTC, panciumihai commented on src/features/characters/charactersSlice.ts
> +                state.error = action.payload as any;
string aici

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +export const getEpisodes = createAsyncThunk('episodes/fetchEpisodes', async (args, { rejectWithValue }) => {
aici vad ca iei doar un count, desi pare ca thunk-ul ar lua episoade

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +        const response = await axios(`https://rickandmortyapi.com/api/episode`);
acelasi lucru legat de URL in constanta si instanta de Axios

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +export const getEpisode = createAsyncThunk('episodes/fetchEpisode', async (args: { episode: number }, { rejectWithValue }) => {
cred ca defapt vrei episodeId aici. episode ma duce cu gandul la un obiect sau string

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +        const response = await axios(`https://rickandmortyapi.com/api/episode/${episode || ''}`);
url-ul si axios

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +            air_date: response.data.air_date,
se putea schimba denumirea din " _ " in camelCase considerand ca ai facut mapare explicita

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +export interface InitialState {
Deci state-ul acesteui slice nu este de tipul InitialState. initialState trebuie sa fie o variabila care reprezinta contentul state-ului la initializare. Poti vedea in in pozele de jos in ce probleme ai intrat. Trebuiau numite din prima de forma "EpisodesState" in cazul de fata.

![image](https://user-images.githubusercontent.com/22646067/194228261-134cd2f8-c634-4ad9-8316-312de34935dc.png)

![image](https://user-images.githubusercontent.com/22646067/194228242-b41a34f9-611b-493f-a2a8-81f477df40af.png)

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +    episodeCount: null,
nu mai folosi null pentru primitive, te incurca tare in typescript si ai defacut check-uri inutile. Pune o valoare default.

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +    episodeCount: number | null,
Nu mai folosi null la declarari in typescript. Daca poti avea variabile neasignate ele se scriu: **episodesCount?: number**. Dar cum am zis aici cel mai corect este sa ai episodesCount: number iar valoarea default sa fie 0.

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +                state.episodeCount = count;
Unde sunt epsioadele? Eu vad doar un count  aici

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +                state.status = 'idle';
nu e corect folosit idle aici

2022-10-06 11:01 UTC, panciumihai commented on src/features/episodes/episodesSlice.ts
> +                state.episodes = action.payload;
Aici functia pare ca ia un singur episod dar returneaza mai multe episoade

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +        const response = await axios(`https://rickandmortyapi.com/api/location`);
povestea legat de url si axios

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +            count: response.data?.info?.count
unde sunt locatiile?

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +        return {
Foloseste types pe raspunsul de la axios ca sa nu mai ajungi la astfel de mapari.

De exemplu pui type la get si ti-l mapeaza singur, exemplu:
![image](https://user-images.githubusercontent.com/22646067/194230224-a3670146-5c19-45d5-9593-14363dbb3d57.png)

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +        const response = await axios(`https://rickandmortyapi.com/api/location/${location || ''}`);
Nu este necesara acest || din ${location || ''}. Se poate scrie direct pentru ca oricum e obligatoriu sa ai un id pe acest path.

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +export interface InitialState {
Redenumeste aceasta interfata

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +            .addCase(getLocations.fulfilled, (state, action) => {
unde sunt locatiile?

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +            .addCase(getLocation.fulfilled, (state, action) => {
aici se intelge ca iei o singura locatia desi tu iei mai multe

2022-10-06 11:01 UTC, panciumihai commented on src/features/locations/locationsSlice.ts
> +                state.status = 'idle';
povestea de la status si idle

2022-10-06 11:01 UTC, panciumihai commented on src/index.tsx
> +const router = createBrowserRouter([
Recomand scrierea de acestor rute in JSX. Sunt curios cum ai trimite un parametru la Characters folosind acest mod de scriere.

2022-10-06 11:01 UTC, panciumihai commented on src/index.tsx
> +    // <React.StrictMode>
Ai comentat asta pentru a nu mai avea request-uri duplicate. Solutia era sa faci clear in useEffect. Poti citi mai multe despre acest StrictMode. In cazul asta e ok si comentat.

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Character/Character.tsx
> +    const { character, status } = useSelector((state: ReduxState) => state.characters);
ai creat la un moment dat un useAppSelector. De ce ai preferat sa nu il folosesti aici?

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Character/Character.tsx
> +            {status === 'idle' ?
nu mai folosi sintaxa X ? Y : Z in JSX pentru structuri asa de mari.
cel mai ok aici era sa scri:
status === 'idle && < Componenta1 />

status !== 'idle' && < Componenta2/>

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Character/Character.tsx
> +                            className={`${styles.status} ${character?.status.toLowerCase() ? styles[character?.status.toLowerCase()] : ''}`}
clsx sau className ar fi facut aceasta parte sa arata mai ok de asemenea cum v-a arata pentru statsul "evil"?

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Characters/Characters.tsx
> +    const lastCardRef = useCallback((post: HTMLElement) => {
asta nu e un Ref. Te-ai complicat tare aici

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Characters/Characters.tsx
> +    const intersectionObserver = useRef<IntersectionObserver>();
Trebuia folosit addEventListener pe scroll pentru load more la scroll

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Characters/Characters.tsx
> +    const onStatusFilterChange = (filter: string) => () => {
Nu este necesar

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Characters/Characters.tsx
> +            <div className={styles.searchBar}>
Nu functioneaza deloc search-ul

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Characters/Characters.tsx
> +                    ref={lastCardRef}
Te rog sa mai citeste despre scop-ul unui Ref. E folosit gresit in contextul asta.

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Characters/Characters.tsx
> +                    setStatusFilter={onStatusFilterChange}
Nu trimite direct useState-uri asa. Orice actiune trimisa catre alta componenta trebuie sa aiba denumirea unui event, pentru ca defapt se trimit callback-uri. De exemplu setSpeciesFilter s-ar fi apelat la onChangeSpeciesFilter.
Insa dupa cum am zis mai sus, aici trimit prea multe props, se poate simplifica cu un simplu onChange si value

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Episode/Episode.tsx
> +    const { episodes, episodeCount } = useSelector((state: ReduxState) => state.episodes);
Aveai un useAppDispatch. Nu era necesar sa declari acel ReduxState, createStore il genereaza automat.

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Episode/Episode.tsx
> +    const onEpisodeChange = (event: ChangeEvent<HTMLSelectElement>) => {
episodeChangeHandler aici. Povestea de naming pentru events

2022-10-06 11:01 UTC, panciumihai commented on src/pages/Location/Location.tsx
> +const Location = () => {
Componenta asta are mult cod duplicat cu Episode.tsx. Cum se putea evit asta?

2022-10-06 11:01 UTC, panciumihai commented on src/utils/types.ts
> +import { InitialState as InitialLocationsState } from "../features/locations/locationsSlice";
Treaba asta putea fi evitata daca denumeai altfel state type-urile

2022-10-06 11:01 UTC, panciumihai commented on src/utils/types.ts
> +export interface ReduxState {
createStore genereaza asta singur

2022-10-06 11:01 UTC, panciumihai commented on src/utils/utils.ts
> +export const createArrayOfLength = (startNumber: number, length: number | null) => {
Nu prea ajuta treaba asta. Pentru scopurile in care l-ai folosit mergea un simplu for... loop

2022-10-06 11:01 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +    setStatusFilter: (filter: string) => () => void,
Foloseste o functie normala aici si daca ai nevoie de ea intr-un onClick de exemplu poti scrie asa:
onClick={()=>setStatusFilter('somthing')}

2022-10-07 06:45 UTC, panciumihai commented on src/components/Filters/CharactersFilter.tsx
> +const CharactersFilter = (props: CharactersFilter) => {
Ai conflict de nume intre componenta si tipul props-urilor acesteia. Numele tipului poate fi redenumit in CharactersFilterProps pentru a evita conflictul.

2022-10-10 15:12 UTC, liviuclement commented on src/features/characters/charactersSlice.ts
> +            .addCase(getCharacters.fulfilled, (state, action) => {
e doar o verificare de pagina vs inca un async thunk + case uri

2022-10-10 16:39 UTC, liviuclement commented on src/features/locations/locationsSlice.ts
> +        return {
Aici nu prea inteleg

2022-10-10 16:51 UTC, liviuclement commented on src/index.tsx
> +const router = createBrowserRouter([
Asta recomanda documentatia react-router-dom, nu prea inteleg ce vrei sa zici

2022-10-10 18:03 UTC, liviuclement commented on src/pages/Location/Location.tsx
> +const Location = () => {
un hook pentru mapSelectOptions?

2022-10-11 09:51 UTC, liviuclement commented on src/components/CharacterCard/CharacterCard.tsx
> +            className={`${styles.status} ${styles[status.toLowerCase()]}`}
am adaugat un background color default

2022-10-13 05:44 UTC, panciumihai commented on src/components/CharacterCard/CharacterCard.tsx
> +            className={`${styles.status} ${styles[status.toLowerCase()]}`}
la ce m-am referit aici este sa pui la status in loc de string, "alive" | "dead" | "unknown". Ca sa dai o idee ce valori sunt acceptate pentru acel field. Asta e ca good practice

2022-10-13 06:13 UTC, panciumihai commented on src/store/features/characters/charactersSlice.ts
> +        const { character } = args;
mergi sa adaugi si Id la final. [ characterId ]

2022-10-13 06:30 UTC, panciumihai approved these changes
O singura mentiune mai am, incearca sa dai nume mai specifice chiar daca scrii o idee mai mult. Ex: adauga Id unde e cazul sau la acordionSlices se poate specifica la cine fac refererie acele slice-uri, gen sa fi mentionat character in nume. In cazul asta e unul singur dar ca idee zic.

In rest arata bine.

2023-01-09 11:28 UTC, merged